2023-09-23 18:46:33,200 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2023-09-23 18:46:33,200 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instabot/bot/bot.py
2023-09-23 18:46:33,200 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2023-09-23 18:46:33,204 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/get_prefill_candidates/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x103f7efd0>: Failed to resolve 'i.instagram.com' ([Errno 8] nodename nor servname provided, or not known)"))
2023-09-23 18:46:33,205 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/qe/sync/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x103f95390>: Failed to resolve 'i.instagram.com' ([Errno 8] nodename nor servname provided, or not known)"))
2023-09-23 18:46:33,206 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/launcher/sync/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x103f977d0>: Failed to resolve 'i.instagram.com' ([Errno 8] nodename nor servname provided, or not known)"))
2023-09-23 18:46:33,207 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/contact_point_prefill/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x103f9dc50>: Failed to resolve 'i.instagram.com' ([Errno 8] nodename nor servname provided, or not known)"))
